spring:
  datasource:
    url: "jdbc:postgresql:skillbox_project"
    username: skillbox
    password: skillbox
  jpa:
    hibernate:
      ddl-auto: update




blog:
  init:
    title: "DevPub"
    subtitle: "Рассказы разработчиков"
    phone: "+7 903 666 44 55"
    email: "arvoglade@gmainl.com"
    copyright: "Артём Гашев"
    copyrightFrom: "2023"
  startGlobalSettings:
    multiuserMode: "YES"
    postPremoderation: "NO"
    statisticsIsPublic: "YES"
